### ISSUE TITLE
Add support for Aligned Rank Transformed data Anova

### ISSUE THREAD

**Issue by clementpoiret** [raphaelvallat/pingouin#47] opened 2019-07-02 10:19 UTC
Good morning,

I had to work on non-normal and heteroscedastic variables but had to compute interactions between those variables. Unfortunately, no methods in your package allow to do so.
I found ART beeing quite straight forward and easy to use. I think it could be very valuable to include ART inside your library. 
The actual solution is to run ARTool through rpy2 which is neither performant nor easy to do. 

Here is the original paper: http://faculty.washington.edu/wobbrock/pubs/chi-11.06.pdf

And here are some R documentation: 
- https://cran.r-project.org/web/packages/ARTool/index.html
- https://cran.r-project.org/web/packages/ARTool/vignettes/art-contrasts.html

Thanks, and have a nice day,
Clément.

**Comment by raphaelvallat** [comment] 2019-07-02 17:44
Hi @clementpoiret! 

Indeed, this looks like a great addition to the [pingouin.nonparametric.py](https://github.com/raphaelvallat/pingouin/blob/master/pingouin/nonparametric.py) file. After a quick read of the paper you sent, I think the 2-factors should be very easy to implement. However, if we want to implement a _N_-way ART, I think we're gonna have to use a regression approach, either using statsmodels or patsy (as a reminder, almost all the ANOVAs in Pingouin are coded in pure ANOVA-style (=no regression) with Pandas).

Do you want to try and work on a pull request (perhaps starting with a 2-factors ART?). Otherwise, I can look into that later in July.

Thanks!
Raphael

**Comment by clementpoiret** [comment] 2019-07-08 15:09
I may try, but I have a lot a work to publish a paper before August, I'll see if I can find the time to do that.

**Comment by raphaelvallat** [comment] 2019-09-28 19:05
Hi @clementpoiret ! I'm closing this issue for now because I won't have the time to implement it in the next few months, and I feel that this may not be the highest priority for Pingouin right now. But, please feel free to reopen! Thanks

**Closed by raphaelvallat** 2019-09-28 19:05 UTC
Labels: enhancement
