### ISSUE TITLE
Effect Size of Cohen D outside the bootstrap CI?

### ISSUE THREAD

**Issue by adam2392** [raphaelvallat/pingouin#97] opened 2020-05-22 20:49 UTC
I'm following the example here https://pingouin-stats.org/generated/pingouin.compute_bootci.html, specifically for Cohen's D, yet I'm getting that the stat is outside of the CI generated.

```
data_dict = np.load('test.npz')
soz_ts = data_dict['x']
nsoz_ts = data_dict['y']
n_ts = soz_ts.shape[1]

[test.npz.zip](https://github.com/raphaelvallat/pingouin/files/4670321/test.npz.zip)

    for i in range(n_ts):
        soz_at_t = soz_ts[:, i]
        nsoz_at_t = nsoz_ts[:, i]
        
        stat = pg.compute_effsize(x=soz_at_t, y=nsoz_at_t, eftype=func)
        ci = pg.compute_bootci(x=soz_at_t, y=nsoz_at_t, 
                          func=func, method=method, 
                          n_boot=n_boot, confidence=confidence)
        
        effectsize_ts.append(stat)
        ci_ts.append(ci)
```

I was wondering if this is a bug?

**Comment by raphaelvallat** [comment] 2020-05-23 00:52
Hi @adam2392,

Thanks for opening the issue. For replicability, could you provide just one example with two 1D arrays, e.g. 
```
x = [..., ]
y = [..., ]
stat = pg.compute_effsize(x, y, ...)
ci = pg.compute_bootci(x, y, ..., seed=)
```
Also, which values were assigned to ``func``, ``method``, ``n_boot`` and ``confidence``?

Looking quickly at your code, it seems that your variable ``x`` has 9 samples while ``y`` has 69 samples. This strong imbalance in sample size is most likely the cause of the unreliable results. Indeed, Pingouin uses a bootstrapping procedure with replacement of all the pairs (Xi, Yi), which means in your case that only the first 9 samples of the second array will be bootstrapped... Please see the code for more details:

https://github.com/raphaelvallat/pingouin/blob/fa53551cb3ff557664e0e85a45833a3421ded0ec/pingouin/effsize.py#L331

Hope this solves the question,
Thanks
Raphael

**Closed** 2020-06-14 01:39 UTC
Labels: question
