### ISSUE TITLE
Assertion failure (-1 <= r <= 1) in power.py when running rm_corr

### ISSUE THREAD

**Issue by willprice** [raphaelvallat/pingouin#87] opened 2020-04-01 13:18 UTC
Hi there,
Thanks for providing this awesome library. I picked it up to run an `rm_corr` test on some data but I'm having issues.

I have 1000 individuals for each of whom I have 8 paired measurements. I have uploaded a pickled dataframe that causes the issue to GDrive (https://drive.google.com/open?id=1gkvGKBth2J8EhmhblsWRdK-eCDlk8zJk).

Here's a snapshot of what the dataframe looks like:
![image](https://user-images.githubusercontent.com/966205/78142702-2add9c80-7425-11ea-8759-6f6a4046f44c.png)

You can reproduce the issue by running:

```python
df = pd.read_pickle('bad_df.pkl')
rm_corr(data=df, x='m2', y='m1', subject='id')
```

which yields the error

```
AssertionError                            Traceback (most recent call last)
<ipython-input-156-86b16d57ef4b> in <module>
----> 1 rm_corr(data=df, x='m2', y='m1', subject='id')

.../lib/python3.7/site-packages/pingouin/correlation.py in rm_corr(data, x, y, subject, tail)
    981     pval = pval * 0.5 if tail == 'one-sided' else pval
    982     ci = compute_esci(stat=rm, nx=n, eftype='pearson').tolist()
--> 983     pwr = power_corr(r=rm, n=n, tail=tail)
    984     # Convert to Dataframe
    985     stats = pd.DataFrame({"r": round(rm, 3), "dof": int(dof),

.../lib/python3.7/site-packages/pingouin/power.py in power_corr(r, n, power, alpha, tail)
    902     # Safety checks
    903     if r is not None:
--> 904         assert -1 <= r <= 1
    905         r = abs(r)
    906     if alpha is not None:

```

If I drop into a debugger I can see that `r = 1.0000184067367273`, perhaps this is due to numerical stability issues?

**Comment by raphaelvallat** [comment] 2020-04-01 16:46
Hi @willprice! Fascinating. Thanks for opening this issue and providing all the data and code required to replicate it. The issue is indeed caused by the fact that the ANOVA/ANCOVA functions that are called internally by rm_corr apply a rounding to the third decimals on the sums of squares. In your case, `m1` and `m2` are very small, which leads to an error. A quick fix for now is to do:

```
df[['m1', 'm2']] *= 100
rm_corr(data=df, x='m2', y='m1', subject='id')
```

which gives the following:

```
           r   dof  pval       CI95%  power
rm_corr  1.0  6999   0.0  [1.0, 1.0]    1.0
```
For longer term solution, we probably need to 1) disable rounding in ANOVA / ANCOVA, or 2) raise a warning when dealing with very small numbers.

Thanks!
Raphael

**Comment by willprice** [comment] 2020-04-01 16:47
Hi @raphaelvallat,
Thanks for the speedy response and workaround, that's great to know! Disabling rounding sounds like a good idea to me :+1: 

Cheers

**Comment by raphaelvallat** [comment] 2020-04-04 20:17
Hi all,

I am actually a bit reluctant to completely disable the rounding of the sums of squares in ANOVA-related functions because I think it will make the overall user experience less enjoyable (i.e. tables will be harder to grasp at a glance if the SSs have 16 decimals...). I think I would therefore prefer to throw a warning or error in the rm_corr function if the data is very small.

But, I'm eager to hear what others people think about this issue, and more generally about the rounding behavior of Pingouin.

Thanks,
Raphael

**Comment by willprice** [comment] 2020-04-05 09:43
Hi Raphael, 

My 2 pence:
I'd expect library functions to return values at the highest precision they're capable of without any truncation, as a library user I expect to be able to control this. Having said that, I agree that for reporting this is definitely not the most desirable behaviour, I want values truncated to reasonable precision.

Maybe an approach like how pandas does it might work for Pingouin:
See `display.precision` in https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html

**Comment by raphaelvallat** [comment] 2020-04-05 20:47
Hi @willprice ! 

I think I like this idea. So, for instance, we could set `pd.set_option('precision', 4)` upon loading Pingouin? I wonder if this should be true for all Pingouin functions, or rather a subset of functions (e.g. ANOVA). I think that 4 decimals is also a good compromise (I believe JASP and JAMOVI have a default of 3 decimal, but I think that for p-values it is better to have at least 4 decimals).

What do people think?

Thanks again

**Comment by sappelhoff** [comment] 2020-04-05 21:06
> I'd expect library functions to return values at the highest precision they're capable of without any truncation, as a library user I expect to be able to control this.

I agree with this sentiment ... so if we can get pandas to DISPLAY the values like pingouin currently does while we still have the full precision when accessing the actual numbers, that'd be great!

**Comment by willprice** [comment] 2020-04-06 10:09
Personally, I would be quite upset if a supporting library changed the options of another core library. I suspect most others would be similarly upset if importing a library would reconfigure a core library.
I had a quick look to see if the display options are baked into the dataframe, or whether they happen at serialisation time, it unfortunately appears the latter is the case:


```python
import pandas as pd

def make_df():
    df = pd.DataFrame({
        'a': [1.214324123412, 31.23141234123],
        'b': ['c', 'd']
    })
    with pd.option_context('display.precision', 3):
        return df

# still prints out with default 6 DPs
print(make_df())
```

I'd suggest having a helper function `pinguoin.set()` a la [`sns.set()`](https://seaborn.pydata.org/generated/seaborn.set.html) which reconfigures pandas printing options.

**Comment by sappelhoff** [comment] 2020-04-28 19:45
I now need the unrounded p-values in one of my analyses, but can't seem to easily get them from pingouin :sob: 

I saw in the ANOVA code, that you add the "formula" to the DF as a `.formula_` attribute:

https://github.com/raphaelvallat/pingouin/blob/c26510c3ae40af0491ada55f9384b35f09d5366c/pingouin/parametric.py#L1154

Wouldn't it be a relatively unobtrusive option to also add a potential `._p_unc_unrounded` as an attribute? @raphaelvallat

**Comment by raphaelvallat** [comment] 2020-04-28 23:07
Hi @sappelhoff ! Which function/parameter are you using exactly? Typically the p-values are **_not_** rounded in Pingouin. However, for some functions like _anovan_ (for _N_-way anova) that depends on statsmodels, the p-values may be rounded internally by statsmodels so there's just no way that we can access the unrounded p-value :grimacing:

**Comment by sappelhoff** [comment] 2020-04-29 09:48
I am using `pingouin.anova` with 2 between factors (balanced), so it should direct me to `anova2`, I guess :thinking: 

but admittedly, this is an analysis where the p-value is probably VERY low (9000 observations in each group). Do you know at what point the p value will be displayed at just 0? --> just so that I can write `p < 0.01` or `001` or `0001` :-)

**Comment by sappelhoff** [comment] 2020-04-29 18:14
Thanks for the suggestions! Unfortunately, neither of `chop_threshold`, nor `precision` were the culprits: It's `f(x,y).sf(z)`

In my case it's looking like this: `f(1, 89990).sf(64331)`, which is too small to be represented, so it returns 0. I tried a few value ... and if my F value were `6*1e2` instead of the `6*1e4`, around which it is, then we'd actually get a p-value: `4.5463468353659744e-132`

:grimacing: I guess this might be expected with so many observations in a simple 2-way anova.

**Comment by raphaelvallat** [comment] 2020-04-30 01:44
Hi,

Quick update: I just pushed a major commit in which I disabled all float rounding in Pingouin's output (see c70b7bcfa3f983bef5368abd85059ce3fad4cbd1). This will be included in the next soon-to-be release.

**Closed** 2020-05-02 16:01 UTC
Labels: enhancement, invalid
