### ISSUE TITLE
ANOVA test returns future warning

### ISSUE THREAD

**Issue by GegznaV** [raphaelvallat/pingouin#322] opened 2022-12-13 20:24 UTC
The example from [documentation](https://pingouin-stats.org/generated/pingouin.anova.html):
```python
import pingouin as pg
df = pg.read_dataset('anova')
aov = pg.anova(dv='Pain threshold', between='Hair color', data=df, detailed=True)
aov.round(3)
```

Returns future warning:
```
c:\Users\user\anaconda3\lib\site-packages\pingouin\parametric.py:992: 
FutureWarning: Not prepending group keys to the result index of transform-like apply.
In the future, the group keys will be included in the index, regardless of whether the 
applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use 

	>>> .groupby(..., group_keys=True)
  sserror = grp.apply(lambda x: (x - x.mean()) ** 2).sum()
```
I used:
```
numpy               1.21.6
pandas              1.5.2
pingouin            0.5.2
scipy               1.9.3
```

**Comment by raphaelvallat** [comment] 2022-12-14 05:44
Duplicate of https://github.com/raphaelvallat/pingouin/issues/311

This should be an easy fix. We just need to add `group_keys=False` to L992: https://github.com/raphaelvallat/pingouin/blob/bc795239cbf5c2f2162fc40073de465846e004a7/pingouin/parametric.py#L992-L997

Feel free to open a PR!

**Comment by raphaelvallat** [comment] 2022-12-15 00:31
Fixed in https://github.com/raphaelvallat/pingouin/pull/323

**Closed** 2022-12-15 19:40 UTC

**Comment by GegznaV** [comment] 2022-12-15 20:58
Thank you for solving this :)
