### ISSUE TITLE
assertion error in power.py // power_corr

### ISSUE THREAD

**Issue by alonappleboim** [raphaelvallat/pingouin#71] opened 2019-11-19 06:20 UTC
((First bug report so pardon the format))

I get this assertion error when running pairwise correlations. This happens if some column combination has less than 4 samples that are both not nan..
I suggest a warning and return np.nan in this case instead of an Error.

Thanks for a cool package!

---------------------------------------------------------------------------
minimal code: 
`pg.pairwise_corr(pd.DataFrame({c: np.random.rand(3) for c in ['A','B','C']}), ['A'])`

---------------------------------------------------------------------------
/Users/user/anaconda3/lib/python3.6/site-packages/pingouin/correlation.py:446: RuntimeWarning: divide by zero encountered in double_scalars
  adj_r2 = 1 - (((1 - r2) * (nx - 1)) / (nx - 3))
/Users/user/anaconda3/lib/python3.6/site-packages/pingouin/effsize.py:146: RuntimeWarning: divide by zero encountered in double_scalars
  se = 1 / np.sqrt(nx - 3)

AssertionError                            Traceback (most recent call last)
<ipython-input-10-7b3892f50ac3> in <module>()
      1 df = pd.DataFrame({c: np.random.rand(3) for c in ['A','B','C']})
----> 2 pg.pairwise_corr(df, ['A'])

~/anaconda3/lib/python3.6/site-packages/pingouin/pairwise.py in pairwise_corr(data, columns, covar, tail, method, padjust, nan_policy, export_filename)
   1065         if covar is None:
   1066             cor_st = corr(data[col1].values, data[col2].values, tail=tail,
-> 1067                           method=method)
   1068         else:
   1069             cor_st = partial_corr(data=data, x=col1, y=col2, covar=covar,

~/anaconda3/lib/python3.6/site-packages/pingouin/correlation.py in corr(x, y, tail, method)
    449     if r2 < 1:
    450         ci = compute_esci(stat=r, nx=nx, ny=nx, eftype='r')
--> 451         pr = round(power_corr(r=r, n=nx, power=None, alpha=0.05, tail=tail), 3)
    452     else:
    453         ci = [1., 1.]

~/anaconda3/lib/python3.6/site-packages/pingouin/power.py in power_corr(r, n, power, alpha, tail)
    909         assert 0 < power <= 1
    910     if n is not None:
--> 911         assert n > 4
    912 
    913     # Define main function

AssertionError:

**Comment by alonappleboim** [comment] 2019-11-19 10:04
In a similar vein, I get an exception when running pairwise_corr in pearsonr when n<2:

------

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-7-ea2ca4d39540> in <module>()
      8     tmp.columns = [' '.join(col).strip() for col in tmp.columns.values]
      9     kcorr = pg.pairwise_corr(tmp.join(meas), padjust='fdr_bh',
---> 10                              columns=[list(tmp.columns), list(meas.columns)])
     11     x = kcorr['X'].str.split(' ',expand=True).rename(columns=dict(enumerate(pkmer.columns.names)))
     12     kcorr = pd.concat([x, kcorr], 1).drop(columns=['X']).rename({'Y': 'measure'})

~/anaconda3/lib/python3.6/site-packages/pingouin/pairwise.py in pairwise_corr(data, columns, covar, tail, method, padjust, nan_policy, export_filename)
   1065         if covar is None:
   1066             cor_st = corr(data[col1].values, data[col2].values, tail=tail,
-> 1067                           method=method)
   1068         else:
   1069             cor_st = partial_corr(data=data, x=col1, y=col2, covar=covar,

~/anaconda3/lib/python3.6/site-packages/pingouin/correlation.py in corr(x, y, tail, method)
    426     # Compute correlation coefficient
    427     if method == 'pearson':
--> 428         r, pval = pearsonr(x, y)
    429     elif method == 'spearman':
    430         r, pval = spearmanr(x, y)

~/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py in pearsonr(x, y)
   3390 
   3391     if n < 2:
-> 3392         raise ValueError('x and y must have length at least 2.')
   3393 
   3394     x = np.asarray(x)

ValueError: x and y must have length at least 2.

**Comment by raphaelvallat** [comment] 2019-11-19 17:29
Hi @alonappleboim! Thanks for the feedback!

- Your first example: it's not a bug but rather a safety net that I've implemented in Pingouin to prevent users from calculating power when the sample size is too small. I would be more in favor of keeping it as is, to be consistent with R, but I'll leave the issue open in case anyone else agrees that it should return a warning + nan.

- For your second example, the error comes from SciPy, and not Pingouin, because you're trying to run a correlation with n=1.

Thanks
Raphael

**Comment by alonappleboim** [comment] 2019-11-19 20:38
thanks for the quick response!
I understand that both these issues (and similar others I've encountered later on) are relevant when calculating corr for a single sample pair, but when executing multiple pairwise corr calculation, it's very disappointing when one problematic sample-pair causes the failure of the entire calculation. I think the better solution would be caught by the calling methods (pairwise_corr in this case) and proper warnings should be thrown.

**Comment by raphaelvallat** [comment] 2019-11-19 22:38
Ok makes sense, I'll try to change the behavior of the pingouin.power functions in future releases so that it returns a warning + np.nan instead of an error. I cannot change SciPy's behavior however so it'll still fail with n<2 (unless I use a Try...Except which I would prefer not for code clarity).
Thanks

**Comment by raphaelvallat** [comment] 2019-11-29 22:17
Hi @alonappleboim! Just pushed a commit to fix this (861914eca0a360fbb9fa2fe9ef1136ac122a29ad). Now the `pingouin.power_corr` function will raise a UserWarning and return a np.nan if the sample size is <= 4. This will be released in the next stable version of Pingouin (December 2019). Thanks again

**Closed by raphaelvallat** 2019-11-29 22:17 UTC
Labels: enhancement
