### ISSUE TITLE
Sorting data farme is changing the results of pairwise_ttests despite same values

### ISSUE THREAD

**Issue by mpcoll** [raphaelvallat/pingouin#151] opened 2021-01-15 17:09 UTC
Hi, thanks for the great package.

I think I ran into a potentially worrisome issue. After sorting a data frame, the pairwise_ttests gives the wrong result after sorting despite the same values. The mixed_anova is not affected.

I encountered it with my own data but reproduced it using the example dataset:

Before sorting

![beforesort](https://user-images.githubusercontent.com/28481638/104755085-02126380-5728-11eb-89fe-0a7f15ade368.png)

After sorting (wrong result)

![aftersort](https://user-images.githubusercontent.com/28481638/104755077-fe7edc80-5727-11eb-8aac-985c49bef04e.png)

**Comment by mpcoll** [comment] 2021-01-15 17:28
Note that sorting by both Subject and the Time solves the issue so a quick fix might be to implement an additional sorting by subjects before extracting the data from the data frame

**Comment by raphaelvallat** [comment] 2021-01-15 18:59
Hi @mpcoll,

This is an absolute nightmare. Thank you for opening the issue. I feel terrible that I wasn't able to see that earlier. Here's what I think is happening:

**1) What is the bug?**

When doing pairwise T-tests with repeated measures data, the current function implicitly assumes that the dataframe is sorted, i.e. that the third row of a given group (= repeated measurements) always belong to the same subject, across all repeated measurements. In other words, that the ordering of the subject is the same across all repeated measurements.

**2) When does it happen?**

It seems that the bug occurs in the following cases when the dataframe is not perfectly sorted by "subject":

- One-way repeated measures pairwise T-tests, only when no missing values are present. Indeed, when missing values are present there was an additional step in the pairwise T-test function that resorted the dataframe by "subject"
- Two-way repeated-measures pairwise T-tests (interaction only)

Note that the bug does not concern non-repeated measures pairwise T-test, since the ordering of the values does not matter.

**3) How can we fix it**

I will try to release a new version as soon as possible. Basically, we need to add some internal sorting of the dataframe to make sure that the ordering of subject is always the same across all repeated measurements. And obviously expand the unit testing with randomly-sorted dataframe to make sure that Pingouin gives valid results in all the aforementioned cases.

In the meantime, I urge all the users to make sure that they're using sorted dataframe, and **check their results against another statistical software** (e.g. JASP). Pingouin is still under development and there are most likely other critical bugs that will be discovered in the next months.

**Comment by raphaelvallat** [comment] 2021-01-15 22:43
Hi,

I just pushed a fix for this error on the develop branch (efc1b1658d18cf28bb370de53d7b734fedd59410). I believe this solves the problem in all the aforementioned cases (i.e. one-way and two-way repeated measures design, with / without missing values). @mpcoll any chance you could try the fix on your own data? You will have to install the develop version of Pingouin.

I'm hoping to release a new Pingouin version with the fix in the coming days given the urgency of the issue.

Thanks again,
Raphael

**Comment by raphaelvallat** [comment] 2021-01-15 23:01
PS: For anyone wanting to reproduce the error, this is the simplest example:

```python
import pandas as pd
import pingouin as pg

df = pd.DataFrame({'time': [0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2],
                   'subj': [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
                  'score': [1, 5, 4, 3, 5, 7, 8, 4, 7, 2, 3, 4]})

df.pairwise_ttests(dv='score', subject='subj', within='time')

df_messy = df.sample(frac=1)
df_messy.pairwise_ttests(dv='score', subject='subj', within='time')
```

**Comment by raphaelvallat** [comment] 2021-01-20 01:24
This issue has now been fixed in the newest stable release of Pingouin (v0.3.9). Closing the issue but please feel free to reopen.

**Closed by raphaelvallat** 2021-01-20 01:24 UTC
Labels: bug :boom:, invalid :triangular_flag_on_post:
