### ISSUE TITLE
Error in intraclass_corr documentation?

### ISSUE THREAD

**Issue by eremingt** [raphaelvallat/pingouin#228] opened 2022-02-02 18:10 UTC
The [documentation for intraclass_corr](https://pingouin-stats.org/generated/pingouin.intraclass_corr.html) states that ICC2 and ICC3 remove mean differences (i.e. ICC 'consistency'), but based on the output, this is only true for ICC3, and ICC2 is 'absolute agreement':

![image](https://user-images.githubusercontent.com/77844820/152212392-3147758c-a194-46ad-b17d-d5bdd9a5769f.png)

I think the behavior is correct according to definitions I've read elsewhere, but the documentation is not accurate.

**Comment by raphaelvallat** [comment] 2022-02-04 00:08
Hi @eremingt,

This function, including the documentation, is a mere duplicate of the ICC function in the R [psych](https://cran.r-project.org/web/packages/psych/psych.pdf) package:

> ICC1 is sensitive to differences in means between raters and is a measure of absolute agreement. ICC2 and ICC3 remove mean differences between judges, but are sensitive to interactions of raters by judges. The difference between ICC2 and ICC3 is whether raters are seen as fixed or random effects.

I am not a statistician and I rarely use the ICC function in my own analyses anyway, so I might not be the best person to solve this issue. How would you edit the documentation? Also, I do not understand the plot that you have attached, could you please give more details?

For future reference, link to the ICC calculation in Pingouin: https://github.com/raphaelvallat/pingouin/blob/dcfdc82bbc7f1ba5991b80717a5ca156617443e8/pingouin/reliability.py#L311-L317

Thank you,
Raphael

**Comment by raphaelvallat** [comment] 2023-06-04 17:40
Closing this but feel free to reopen

**Closed by raphaelvallat** 2023-06-04 17:40 UTC
Labels: docs/testing:book:
