### ISSUE TITLE
Wilcoxon signed rank sum for univariate comparison to fixed value

### ISSUE THREAD

**Issue by thomas-haslwanter** [raphaelvallat/pingouin#186] opened 2021-07-19 21:05 UTC
Currently the Wilcoxon test is implemented only for a paired test.
I think it would be very helpful also to implement it for comparison of a not-normally distributed sample to a fixed value, similar to 
scipy.stats.wilcoxon

**Comment by thomas-haslwanter** [comment] 2021-07-20 08:21
Attached a piece of code. IMPORTANT: pingouin gets the same W-value, but a different p-value! Please check
``
import numpy as np
from scipy import stats
import pingouin as pg

offset = 5

data = np.random.randn(100) + offset

stats.wilcoxon(data-offset)
Out[4]: WilcoxonResult(statistic=2440.0, pvalue=0.7700896655852555)

pg.wilcoxon(data, offset * np.ones_like(data))
Out[5]: 
           W-val       tail     p-val       RBC  CLES
Wilcoxon  2440.0  two-sided  0.771404 -0.033663  0.56
``

**Comment by raphaelvallat** [comment] 2021-07-20 15:39
Hi @thomas-haslwanter,

The difference in p-value is caused by the fact that Pingouin automatically applies a correction for non-uniformity (as explained in the documentation of the function):

```python
wval, pval = scipy.stats.wilcoxon(x, y, zero_method='wilcox', correction=True, alternative=tail)
```

Got it for the proposed change, should be pretty straightforward to implement. I'll work on this for the next release 👍 

Thanks,
Raphael

**Comment by raphaelvallat** [comment] 2021-08-06 01:40
Added in d94ee0a8da7ba8106b5149b5b40ffdd40678642a

**Comment by raphaelvallat** [comment] 2021-08-13 18:02
This has been released in the new stable version of Pingouin ([v0.4.0](https://github.com/raphaelvallat/pingouin/releases/tag/v0.4.0)). Please make sure to upgrade with `pip install --upgrade pingouin`.

Thank you -- closing the issue.

**Closed by raphaelvallat** 2021-08-13 18:02 UTC
Labels: feature request :construction:
