### ISSUE TITLE
Unexpected results in semi-partial correlation with Spearman/Kendall

### ISSUE THREAD

**Issue by nrcjea001** [raphaelvallat/pingouin#147] opened 2020-12-12 11:26 UTC
As a test, I generated correlated variables x and y. I then set x_test to x and ran a semi-partial correlation of xtest against y, controlling for the effect x on y. As one would expect, the pearson semi-partial correlation of this is zero. However, when applying Spearman and Kendall, the result is non-zero.

The Spearman and Kendall result was 0.14 and 0.11 respectively. Although it is low using the following dummy dataset, the data I am working with produces a very high semi-partial correlation around 0.8 which does not make sense.

````
df=pd.DataFrame({"y":[1,2,3,4,5,6,7,8,9,10],"x":[1,3,5,8,7,10,13,14,18,21]})
print(df.corr())
df['x_test']=df['x']
partial_corr(data=df,x='x_test',y='y',y_covar=['x'], 
             method='spearman')['r'].values

Out:

          y         x
y  1.000000  0.985318
x  0.985318  1.000000

array([0.13939394])
````

**Comment by raphaelvallat** [comment] 2020-12-13 19:39
Hi @nrcjea001,

I believe this is caused by the very low sample size and non-normality of the data that you're using in this example. In the example below, I generate two (normal) correlated variables with n=100, and as you can see the Spearman semi-partial correlation is very close to zero.

![image](https://user-images.githubusercontent.com/25703792/102021806-657b3100-3d37-11eb-8089-bdd1b9b6d938.png)

Furthermore, since the semi-partial correlation is calculated on the residuals (which are assumed to be normally distributed in linear regression), I think it makes more sense to use Pearson as the default for semi-partial correlation, instead of Spearman which will use the rank of the residuals.

Thanks,
Raphael

**Comment by nrcjea001** [comment] 2020-12-14 03:04
Hello, the following example is more appropriate:

![image](https://user-images.githubusercontent.com/26452178/102035729-9b252600-3dda-11eb-8049-c5c4a52d8080.png)

**Comment by raphaelvallat** [comment] 2020-12-15 00:17
Hi @nrcjea001,

In your example, the Y variable is not normal but binary, therefore a linear regression (Y ~ X) is not appropriate and will result in non-normal residuals, which most likely leads to invalid ranks for the Spearman correlation. Furthermore, the fact that your covariate has exactly the same values as the X variable is clearly sub-optimal. In fact, I've tried to run your example in the [ppcor](https://rdrr.io/cran/ppcor/) R package (which uses the inverse covariance matrix instead of residuals to calculate the semipartial correlation), and I get the following error:

![image](https://user-images.githubusercontent.com/25703792/102151186-2a582b00-3e27-11eb-8353-92570adc3381.png)

All that to say that I'm not sure there are any changes required in Pingouin source code here, except perhaps returning a warning or error when a covariate has the same values as the X or Y variable. Let me know what you think.

Thanks
Raphael

**Comment by nrcjea001** [comment] 2020-12-15 02:39
Hi @raphaelvallat

Pearson rests on an assumption of normality. However, Spearman's correlation is a rank based correlation measure; it's non-parametric and does not rest upon an assumption of normality. Same with Kendall. Its surprising therefore that the Pearson method provides the correct result when the others do not.

I do not think the issue is that Y is binary. The issue is the formulae for partial correlation when method Spearman/Kendall is chosen or when X/Y are non-normal. In my view, a different formulae should be applied to suit the characteristics of the problem. For example, when Y is binary should it not be a logistic regression rather than a linear regression?

I am not sure what the formulae for each should be but perhaps it would be good to look into it. As for the ppcor package in R, it would be good to apply a small amount of variation in xtest to avoid the singular value problem (the idea is to have x and xtest very similar so that we can clearly observe the effect of x being removed from y in the partial correlation which should then imply a partial correlation of zero between xtest and y).

**Comment by raphaelvallat** [comment] 2020-12-15 05:42
Hi @nrcjea001,

Sorry I wasn't clear re: normality, I was talking about the assumption of normality of the residuals of Y ~ X, not the normality of the x and y variable in the calculation of the correlation. In that specific case, I do agree that a logistic regression would be more adequate. However, there are very few packages/software that implements semi-partial correlation, and I've never seen one with logistic regression if Y is binary. So, I would say that unless we find 1) another package that implements it, 2) a scientific article proving that this approach is valid, then I would be against implementing it in Pingouin. Please do let us know if you find one of the above.

Thanks,
Raphael

**Comment by nrcjea001** [comment] 2020-12-17 05:29
Hi @raphaelvallat 

I have been doing some digging, and I was just want to confirm if your code follows the same principle. In the Spearman case, the partial correlation is the pearson correlation of the residuals of the linear regression between the ranks of the variables in question. [link here](https://imaging.mrc-cbu.cam.ac.uk/statswiki/FAQ/partsp#:~:text=It%20is%20possible%20to%20produce%20partial%20nonparametric%20correlations.&text=It%20follows%20from%20this%20equivalence,ranks%20of%20the%20partialled%20variables.)

The kendall is something else entirely [link here](https://www.itl.nist.gov/div898/software/dataplot/refman2/auxillar/partktau.htm)

**Comment by raphaelvallat** [comment] 2020-12-17 22:12
Hi @nrcjea001,

The source code of the partial_corr function can be found [here](https://github.com/raphaelvallat/pingouin/blob/334e41003499ccd8137bda193e96d463d26ff32e/pingouin/correlation.py#L576). Pingouin indeed uses a standard regression approach to calculate the residuals of a linear regression (X ~ covar and/or Y ~ covar). These residuals are then passed to the main correlation function ([pingouin.corr](https://github.com/raphaelvallat/pingouin/blob/334e41003499ccd8137bda193e96d463d26ff32e/pingouin/correlation.py#L315)) which internally uses SciPy to calculate the Pearson, Spearman and Kendall coefficients.

**Comment by raphaelvallat** [comment] 2021-01-16 16:40
Closing this issue but please feel free to reopen.

**Comment by krassowski** [comment] 2021-06-28 17:21
Perhaps multi-level correlations would be appropriate in this case? For example see https://easystats.github.io/correlation/articles/multilevel.html

As for the use of binary variables with semi-partial correlations in non-singular cases the R implementation returns reasonable p-value estimates, but pingouin can return a lot of false positives. I guess there must be some numerical issue in the code, as for well-behaved data there is no such a problem (the results agree between the Python and the R implementations).

**Comment by raphaelvallat** [comment] 2021-06-29 18:54
Hi @krassowski,

> As for the use of binary variables with semi-partial correlations in non-singular cases the R implementation returns reasonable p-value estimates, but pingouin can return a lot of false positives.

Can you provide here some example code/results of Pingouin and R? That would be really helpful.

Thanks

**Comment by krassowski** [comment] 2021-06-29 22:05
The data I have is ugly, but this is the real-world data.

[pingouin_repro.csv](https://github.com/raphaelvallat/pingouin/files/6736710/pingouin_repro.csv)

```python
from pandas import read_csv
df = read_csv('pingouin_repro.csv', index_col=0)
df.value_counts()
```

```
x         y    z  
0.321601  0.0  1.0    281
               0.0    271
          1.0  1.0    207
               0.0     21
0.370922  0.0  1.0      1
0.452334  0.0  1.0      1
1.000000  1.0  1.0      1
1.547666  1.0  1.0      1
1.629078  0.0  1.0      1
1.896629  1.0  1.0      1
```

```
df.corr(method='pearson')
```

x | y | z
-- | -- | --
1.000000 | 0.063812 | 0.054962
0.063812 | 1.000000 | 0.374630
0.054962 | 0.374630 | 1.000000


I agree the data like would ideally be analysed differently, but in real world this is just a subset of a larger dataset in which the majority of variables points is not like that.

### Pingouin

```python
from pingouin import partial_corr

partial_corr(df, x='x', y='y', covar='z', method='spearman')
```
n | r | CI95% | p-val
-- | -- | -- | --
786 | 0.185095 | [0.12, 0.25] | 1.761476e-07


R via rpy2:

```python
from rpy2.robjects import pandas2ri
from rpy2.robjects.packages import importr

ppcor = importr('ppcor')
pandas2ri.activate()
ppcor.pcor_test(x=df.x, y=df.y, z=df.z, method='spearman')
```


estimate | p.value | statistic | n | gp | Method
-- | -- | -- | -- | -- | --
0.015809 | 0.658306 | 0.442422 | 786 | 1.0 | spearman

I'm mostly concerned with very low p-value returned by the Pingouin, but the difference in estimates is also substantial

### Semi-partial

Semi-partial on the second variable (to match behaviour of `ppcor::spcor.test`):

```python
partial_corr(df, x='x', y='y', y_covar='z', method='spearman')
```

n | r | CI95% | p-val
-- | -- | -- | --
786 | 0.003497 | [-0.07, 0.07] | 0.922063


```python
ppcor.spcor_test(x=df.x, y=df.y, z=df.z, method='spearman')
```

estimate | p.value | statistic | n | gp | Method
-- | -- | -- | -- | -- | --
0.015773 | 0.659034 | 0.441415 | 786 | 1.0 | spearman

**Comment by krassowski** [comment] 2021-06-29 22:11
Let's consider a simpler case:

```python
df = read_csv('pingouin_repro.csv', index_col=0)
df = df[df.x < 0.38]
df.value_counts()
```

```
x         y    z  
0.321601  0.0  1.0    281
               0.0    271
          1.0  1.0    207
               0.0     21
0.370922  0.0  1.0      1
```

Pingouin:


```python
partial_corr(df, x='x', y='y', covar='z', method='spearman')
```

n | r | CI95% | p-val
-- | -- | -- | --
781 | 0.185361 | [0.12, 0.25] | 1.850181e-07

ppcor:

```python
ppcor.pcor_test(x=df.x, y=df.y, z=df.z, method='spearman')
```


estimate | p.value | statistic | n | gp | Method
-- | -- | -- | -- | -- | --
-0.035959 | 0.31586 | -1.003649 | 781 | 1.0 | spearman

**Comment by raphaelvallat** [comment] 2021-06-30 22:24
Thanks @krassowski. I'm re-opening this issue for visibility.

Pingouin and ppcor uses very different strategies for calculating the partial correlation coefficient. Pingouin follows the traditional definition, which is a correlation between the residuals of a linear regression (on the ranks [in the case of a Spearman partial correlation](https://imaging.mrc-cbu.cam.ac.uk/statswiki/FAQ/partsp)). Ppcor however uses an inverse covariance matrix to calculate the partial correlation coefficient (see [here](https://github.com/cran/ppcor/blob/1631a00104ac08819ef7c757eb380c6de451b5d8/R/ppcor_v1.01.R#L23-L34)). We cannot do that in Python for a Spearman partial correlation because there's no equivalent function [to the R function](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/cor): `cov(x, method="spearman")`. 

I do not know which of these two methods yield the most "ground-truth" or accurate results in the case of a Spearman partial correlation with binary variables. In Pingouin, the residuals of the linear regression will certainly be invalid (and therefore the ranks too), but I think that the R method will also be invalid, since the covariance will be calculated on ranks that are most likely wrong because of the ties caused by the binary variable.

My recommendation would therefore be to never use a Spearman correlation when any of the variables is binary.

Let me know what you think,
Raphael

**Comment by krassowski** [comment] 2021-07-02 10:10
We can perform a simulation to see what are the rates of rejections when holding `x` and `y` constant (randomly generated with `seed = 0`) while randomly changing `z`:

```python
import random
import warnings

from pandas import DataFrame, concat
from pingouin import partial_corr, corr
```

## `pingouin` in Python

### Pearson in `pingouin`

For `pearson` all looks fine:

```python
random.seed(0)

x = list([random.choice([0, 1]) for _ in range(100)])
y = list([random.choice([0, 1]) for _ in range(100)])
non_partial_corr = corr(x, y)

results = []

for i in range(10**4):
    df = DataFrame({
        'x': x,
        'y': y,
        'z': [random.choice([0, 1]) for _ in range(100)]
    })
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        result = partial_corr(df, x='x', y='y', covar='z', method='pearson')
    results.append(result)

results = concat(results)
print(non_partial_corr)
results['p-val'].hist();
```

> ```
>           n         r          CI95%     p-val   BF10     power
> pearson  100  0.040129  [-0.16, 0.23]  0.691809  0.135  0.068089
> ```

> ![image](https://user-images.githubusercontent.com/5832902/124255675-57013500-db22-11eb-86b4-6fc72a489a73.png)

```python
results['r'].hist();
```

> ![image](https://user-images.githubusercontent.com/5832902/124258814-bad92d00-db25-11eb-9067-bcd9cc7010ce.png)

### Spearman in `pingouin`

But for `spearman` we get a lot of rejections, and the estimates are all over the place:

```python
random.seed(0)

x = list([random.choice([0, 1]) for _ in range(100)])
y = list([random.choice([0, 1]) for _ in range(100)])
non_partial_corr = corr(x, y)

results = []

for i in range(10**4):
    df = DataFrame({
        'x': x,
        'y': y,
        'z': [random.choice([0, 1]) for _ in range(100)]
    })
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        result = partial_corr(df, x='x', y='y', covar='z', method='spearman')
    results.append(result)

results = concat(results)
print(non_partial_corr)
results['p-val'].hist();
```

> ```
>           n         r          CI95%     p-val   BF10     power
> pearson  100  0.040129  [-0.16, 0.23]  0.691809  0.135  0.068089
> ```

> ![image](https://user-images.githubusercontent.com/5832902/124255785-76985d80-db22-11eb-968b-dd04c797ee3e.png)

```python
results['r'].hist();
```

> ![image](https://user-images.githubusercontent.com/5832902/124258690-98dfaa80-db25-11eb-9a0e-e0317a408e10.png)

## `ppcor` in R

How does it compare to R ppcor implementation?

```python
from rpy2.robjects import pandas2ri
from rpy2.robjects.packages import importr

stats = importr('stats')
ppcor = importr('ppcor')

pandas2ri.activate()
```

### Pearson in `ppcor`

```python
random.seed(0)

x = list([random.choice([0, 1]) for _ in range(100)])
y = list([random.choice([0, 1]) for _ in range(100)])
non_partial_corr = stats.cor_test(df.x, df.y, method='pearson')

results = []

for i in range(10**4):
    df = DataFrame({
        'x': x,
        'y': y,
        'z': [random.choice([0, 1]) for _ in range(100)]
    })
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        result = ppcor.pcor_test(x=df.x, y=df.y, z=df.z, method='pearson')
    results.append(result)

results = concat(results)
print(non_partial_corr)
results['p.value'].hist();
```

> ```
> 	Pearson's product-moment correlation
> 
> data:  [redacted]
> t = 0.39757, df = 98, p-value = 0.6918
> alternative hypothesis: true correlation is not equal to 0
> 95 percent confidence interval:
>  -0.1575312  0.2346969
> sample estimates:
>        cor 
> 0.04012862 
> ```

> ![image](https://user-images.githubusercontent.com/5832902/124258895-d6443800-db25-11eb-8232-ef3c8ee39b50.png)


```python
results['statistic'].hist();
```

> ![image](https://user-images.githubusercontent.com/5832902/124258277-1e168f80-db25-11eb-8fa2-87f5d9cc95d9.png)


### Spearman in `ppcor`

```python
random.seed(0)

x = list([random.choice([0, 1]) for _ in range(100)])
y = list([random.choice([0, 1]) for _ in range(100)])
non_partial_corr = stats.cor_test(df.x, df.y, method='spearman')

results = []

for i in range(10**4):
    df = DataFrame({
        'x': x,
        'y': y,
        'z': [random.choice([0, 1]) for _ in range(100)]
    })
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        result = ppcor.pcor_test(x=df.x, y=df.y, z=df.z, method='spearman')
    results.append(result)

results = concat(results)
print(non_partial_corr)
results['p.value'].hist();
```

> ```
>	Spearman's rank correlation rho
> 
> data: [redacted]
> S = 159963, p-value = 0.6918
> alternative hypothesis: true rho is not equal to 0
> sample estimates:
>        rho 
> 0.04012862
> ```

> ![image](https://user-images.githubusercontent.com/5832902/124257784-9cbefd00-db24-11eb-940e-7857f79ccf18.png)


```python
results['statistic'].hist();
```

> ![image](https://user-images.githubusercontent.com/5832902/124258451-4f8f5b00-db25-11eb-8826-5aa4c9cb8f0c.png)

**Comment by krassowski** [comment] 2021-07-02 10:23
We can conclude that the estimates and p-values for spearman with binary values are wrong for a certain definition of wrong:
- they are different than in `ppcor`
- they produce way more rejections than we would expect
- they produce wrong estimates (for generated data median of `r = 0.04` would be expected, but we get as many positive as negative coefficients almost an order of magnitude greater in absolute value)

The way the binary data was generated is neat because we would expect the same coefficient values for pearson and for spearman; while pearson behaves well, the spearman in `pingouin` appears to be almost random.

I would proceed with adding a warning to the documentation about this use case, because users coming from R may expect this to work as in `ppcor`. I will investigate the code next time I get an opportunity.

**Comment by raphaelvallat** [comment] 2021-07-02 16:41
Thanks for this exhaustive test @krassowski! Two options indeed:

1) Return a warning (or even error) when users run a Spearman partial correlation with at least one binary variable. We'll also have to check if this affects other robust correlation methods (e.g. bicor, percbend, skipped).

2) Rewrite the [pg.partial_corr](https://pingouin-stats.org/generated/pingouin.partial_corr.html) function to use the inverse-covariance matrix instead of a regression approach. I think it shouldn't be too hard to re-implement the cov(method="spearman") in Python, as we just need to apply a rank transform to the data before calculating the covariance matrix. I like this approach because it will be significantly faster, and we'll get the same results as [ppcor](https://github.com/cran/ppcor/blob/master/R/ppcor_v1.01.R). However, it also means that the partial_corr function will not be able to support the robust correlation methods, but only Pearson and Spearman (consistent with ppcor).

**Comment by raphaelvallat** [comment] 2021-07-16 19:23
FYI I have just pushed a commit on the develop branch (81d1aafa0826c34e3ce8ed499a87ae5ad86843d1) to re-implement the partial correlation using the same method as ppcor:

https://github.com/raphaelvallat/pingouin/blob/81d1aafa0826c34e3ce8ed499a87ae5ad86843d1/pingouin/correlation.py#L781-L822

We're now getting exactly the same results as ppcor for partial/semi-partial correlations (either Pearson or Spearman). I think this will be included in the next stable release of Pingouin. Feel free to test it out and let me know if you find any errors or bugs!

**Comment by raphaelvallat** [comment] 2021-08-13 18:06
This has been included in the new stable version of Pingouin ([v0.4.0](https://github.com/raphaelvallat/pingouin/releases/tag/v0.4.0)). Please make sure to upgrade with `pip install --upgrade pingouin`.

Thanks,
Closing the issue.

**Closed by raphaelvallat** 2021-08-13 18:06 UTC
Labels: invalid :triangular_flag_on_post:

**Comment by CrafterKolyan** [comment] 2021-08-16 10:23
Will there be an implementation for `kendall` correlation (there is in `ppcor`)?
Or is it just a small error that here
https://github.com/raphaelvallat/pingouin/blob/81d1aafa0826c34e3ce8ed499a87ae5ad86843d1/pingouin/correlation.py#L750-L751
we just need to add `'kendall'` to a list?

**Comment by raphaelvallat** [comment] 2021-08-17 21:04
@CrafterKolyan the Kendall partial correlation is not supported. To implement it, we need to:

1. Calculate the _Kendall_ covariance matrix (R code [here](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/cor.html)) — though I'm not sure how it is difference from a regular covariance matrix (?)
2. Update the calculation of the statistic and p-value as in ppcor:

https://github.com/cran/ppcor/blob/1631a00104ac08819ef7c757eb380c6de451b5d8/R/ppcor_v1.01.R#L37-L44

If you'd like to, feel free to open a PR!
Thanks,
Raphael
